mejoras en fspatch

diff --git a/common/System/Developer/GenOSToolkit/FSPatch b/common/System/Developer/GenOSToolkit/FSPatch
--- a/common/System/Developer/GenOSToolkit/FSPatch
+++ b/common/System/Developer/GenOSToolkit/FSPatch
@@ -1,9 +1,35 @@
 #!/bin/sh
 
-# Check for --nsm option
+# Function to show usage
+show_usage() {
+    echo "Usage: $0 [--nsm]"
+    echo ""
+    echo "Options:"
+    echo "  --nsm    Clone without submodules (no submodules mode)"
+    echo "  --help   Show this help message"
+    echo ""
+    exit 1
+}
+
+# Check for arguments
 NSM_MODE=false
-if [ "$1" = "--nsm" ]; then
-    NSM_MODE=true
+if [ $# -gt 1 ]; then
+    echo "Error: Too many arguments provided."
+    show_usage
+elif [ $# -eq 1 ]; then
+    case "$1" in
+        --nsm)
+            NSM_MODE=true
+            ;;
+        --help|-h)
+            show_usage
+            ;;
+        *)
+            echo "Error: Unknown argument '$1'"
+            echo ""
+            show_usage
+            ;;
+    esac
 fi
 
 echo
@@ -31,10 +57,10 @@ cd ~/.newFS
 
 if [ "$NSM_MODE" = true ]; then
     echo "$(tput setaf 6)Cloning ostree without submodules...$(tput sgr0)"
-    git clone https://github.com/lucasengithub/OSFS
+    git clone --recurse-submodules https://github.com/lucasengithub/OSFS
 else
     echo "$(tput setaf 6)Cloning ostree with submodules...$(tput sgr0)"
-    git clone --recurse-submodules https://github.com/lucasengithub/OSFS
+    git clone https://github.com/lucasengithub/OSFS
 fi
 
 cp -rvf ~/.newFS/OSFS/common/* /
